### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Mostafa-ebrahimi** [raff-k/Lslide#1]
I cant understand how does it execute?

**Comment by raff-k** [comment]
jupp, I haven't written a vignette, yet :-/
But which function you mean? Maybe I can provide you some code example ...

**Comment by Mostafa-ebrahimi** [comment]
The uploaded file seems to be confusing.
There are some simple questions for me that I just know the topic which is"automated dection of landslides using high-resolution LiDAR DTM data"

Where is the main script?
Where is input?
What will be output?

**Comment by raff-k** [comment]
The objective of my [thesis](https://github.com/raff-k/Lslide-thesis/raw/master/Knevels2017_AutomaticLandslideDetection_Thesis.pdf) was the object-oriented detection of landslides in high-resolution DTM data. Therefore, I created multiple helper functions. Meaning, there is no single function which gives landslide polygons as return. The scripts you can find [here](https://github.com/raff-k/Lslide-thesis).

**_Briefly:_** The **first** step was the derivation of land surface parameters etc. using SAGA and GRASS GIS. In the **second** step the slope was segmented using the segmentation function of the package. Based on the resulting polygon-shapefile neighborhood-statistics were culculated in the **thrid** step. Here, the corresponding neighborhood functions of the package were used. They were mostly created related to the functions of the eCognition handbook. In the **last step**, landslide parts were detected using a data-driven kmeans thresholding procedure.

**Comment by Mostafa-ebrahimi** [comment]
Great!!!!!!!!!!!!!!!!Many Thanks!!!!!!!!!!!!!!

**Comment by Mostafa-ebrahimi** [comment]
Thanks alot
